reasoning_level = "high"
hide_agent_reasoning = true
network_access = true
web_search_request = true
approval_policy = "never"
model = "gpt-5.2-codex"
mmodel_reasoning_effort = "medium"
sandbox_mode = "workspace-write"
personality = "pragmatic"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.2-codex"
